### ISSUE TITLE
Feature: Customizable route id (react-router)

### ISSUE THREAD

**Issue by jfairley** [oedotme/generouted#123]
`react-router` generates a route id for each route, but also exposes an attribute for a user-defined id. I would like to see this functionality exposed through generouted.

## How is `Route.id` useful?

One reason `Route.id` is useful is for accessing loader data. `react-router` allows child nodes to fetch loader data from parent routes. There are a number of ways to achieve this, but the most straight-forward requires knowing the route `id`.

### Example

To take advantage of [`useRouteLoaderData()`](https://reactrouter.com/en/main/hooks/use-route-loader-data)

`src/pages/(private)/_layout.tsx`

```ts
export function Loader() {
  const user = /* fetch */;
  return user;
}
```

`src/pages/(private)/some/custom/path.tsx`

```ts
export default function Page() {
  const user = useRouteLoaderData("(private)@(private)/_layout")
  // ...
}
```

Clearly, this requires intimate knowledge of the full route tree.

## Proposal

Support an optional well-known const for applying `id` to the generated route.

## Example

```ts
export const ID = "load-user-data";
```

https://github.com/oedotme/generouted/blob/v1.15.8/packages/generouted/src/react-router.tsx#L21

```diff
- return { ...index, Component: Page, ErrorBoundary: module?.Catch, loader: module?.Loader, action: module?.Action }
+ return { ...index, Component: Page, ErrorBoundary: module?.Catch, loader: module?.Loader, action: module?.Action, id: module?.ID }
```

## Alternatives

Aside from hard-coding the anticipated id as generated by react-router, there are a few current work-arounds, all of which are less palatable than declaring an `ID`.

1. `useMatches().find(({ data }) => /* data matches "user" */)?.data`
   - https://reactrouter.com/en/main/hooks/use-matches
3. `<Outlet context={user} />` / `const user = useOutletContext()`
   - My concern with this pattern is a middle-man layout changing the data unintentionally. 
4. custom react context

**Comment by jfairley** [comment]
Btw, I'm happy to try a go at a pull-request if you prefer it or are too busy.

**Comment by oedotme** [comment]
Hey @jfairley, thanks a lot for the proposal and the willing to contribute!

I was considering to have each route `id` matching it's full path without the extension which would be unique, then to make the current `id` value private for internal use. In the example you've provided, it would be `(private)/_layout` instead of `(private)@(private)/_layout` and so on.

This way you can directly guess what route to fill in based on the exact file path. On top of that, it can be generated as a type, providing auto-completion for the `useRouteLoaderData` hook similar to the `useParams` hook.

Also having the full path can be useful to be accessed in other cases, I found myself needing this couple of times before.

I believe having a type-safe `useRouteLoaderData` hook would make the experience easier without the need of guessing ids, but please let me know what you think.

**Comment by jfairley** [comment]
Hi @oedotme. Thanks for the response!

I also considered going with the partial file path as the `id` automatically, so I'm happy to hear you had considered that. I think that would be a great default regardless of whether we implement something like `export const ID`.

Lemme know if you want me to take a crack at that.

**Comment by jfairley** [comment]
Hey @oedotme, I like the latest change (`v.1.15.9`). The generated paths are clear and predictable. 👍🏼 

I look forward to type-safe `useRouteLoaderData`!

---

**Comment by oedotme** [comment]
Hey @jfairley, yes we can close this issue — I'll make sure to leave a comment here tho once it's added. Thanks!
