### ISSUE TITLE
Question: usage without TypeScript

### ISSUE THREAD

**Issue by Khalilsqu** [oedotme/generouted#156]
### Describe the Bug

Can this be used without typescript? 

I am trying it without typescript now!! 
I observe that it does not reload after code changes. there are also many strange behavoirs!! 

### Generouted Version

latest 

### Your Example Website or App or Reproduction

just want to ask a question

### Steps to Reproduce the Bug or Issue

normal use

### Expected Behavior

normal use

### Platform

windows

**Comment by Khalilsqu** [comment]
thanks,
Just tested and yes it works without TS.

**Comment by oedotme** [comment]
@Khalilsqu You can use `generouted` without TypeScript with no issues, the optional generated `router.ts` file contains only types for the type-safety that you can actually benefit from while you're using just JavaScript. You could disable generating this file by simply not using the Vite plugin as @ferretwithaberet suggested but I wouldn't recommend that.

On the run-time level, both `.tsx` and `.jsx` files are supported for routes declaration. You can declare all your routes with the `jsx` extension instead of `tsx` as most of the example on this repo.
