### ISSUE TITLE
Question about how to do SEO on a per page basis.

### ISSUE THREAD

**Issue by samhren** [oedotme/generouted#164]
How would I use custom meta tags on a per page basis with generouted? As of right now I can use react-helmet to do it dynamically, but this loads after the SEO is already generated. Is there any way I can add tags to the HTML, hardcoded? Thanks.

**Comment by oedotme** [comment]
@samhren Vite supports SSR and you could do pre-rendering in order to generate the content of the pages with the `meta` tags included. Here's Vite's [official docs for pre-rendering and (Static Site Generation) SSG](https://vitejs.dev/guide/ssr#pre-rendering-ssg).

The main thing you'd need from `generouted` is the `routes` object/array to create a [`StaticRouter`](https://reactrouter.com/en/main/routers/create-static-router), in this step you could also setup the `meta` tags for SSR.

With an SSR entry in place, you could either use SSR or SSG by running a script to generate full HTML versions for all routes to be served statically.

There was a setup at [Render `a50fc66`](https://github.com/oedotme/render/tree/a50fc66bb35e9dff39a62de39e33c1854b7c7604) for pre-rending before it was removed. You can refer to the [`server.ts` setup](https://github.com/oedotme/render/blob/a50fc66bb35e9dff39a62de39e33c1854b7c7604/src/server.tsx) and the [`prerender.ts` script](https://github.com/oedotme/render/blob/a50fc66bb35e9dff39a62de39e33c1854b7c7604/prerender.ts). You'll likely need to change couple of things for the router new APIs and also your usage.

Hope that helps!
