### ISSUE TITLE
Upgrade Micromatch package to resolve vulnerability issues

### ISSUE THREAD

**Issue by Here2Huynh** [oedotme/generouted#177]
### Describe the Bug

This package was flagged by my vulnerability scan. It recommends this package to upgrade micromatch to 4.0.8 or higher.

<img width="668" alt="image" src="https://github.com/user-attachments/assets/94ac01d5-4070-4564-85cf-0ea335a9311b">
<img width="668" alt="image" src="https://github.com/user-attachments/assets/022167eb-5cc4-490b-ba83-2154e66e8f32">

### Generouted Version

1.19.6

### Your Example Website or App or Reproduction

n/a

### Steps to Reproduce the Bug or Issue

1. Install @generouted/react-router
2. Run vulnerability scan tool

### Expected Behavior

Vulnerability exploits should not be present for security.

### Platform

- OS: agnostic
- Browser: agnostic
- Browser version: agnostic

**Comment by oedotme** [comment]
Thanks for reporting. This is caused by the `fast-glob` dependency used by Vite. `generouted` itself doesn't have direct dependencies. Please follow-up on that here: https://github.com/mrmlnc/fast-glob/issues/457, https://github.com/mrmlnc/fast-glob/pull/456

For the meanwhile, you may try to upgrade to `micromatch@4.0.8` manully.
