### ISSUE TITLE
support next.js v13's experimental "app" directory

### ISSUE THREAD

**Issue by aladdin-add** [oedotme/generouted#69]
Thanks for making this awesome tool! 🙌

next.js v13 has introduced an experimental feature: "app" directory, to replace the old `page`: https://beta.nextjs.org/docs/routing/fundamentals#the-app-directory

Are you interested in implementing it?

**Comment by oedotme** [comment]
Hey @aladdin-add

Short answer is no. IMHO I find it a bit difficult to work with the new `app` directory, and with a lot of files in comparison with the `pages` conventions that was the initial inspiration to `generouted`. I think the main `app` directory strengths aren't the conventions, but other features specific to Next.js as a framework.

Also, personally I prefer route-based definition of loader, error and pending states in one file, instead of creating three more files besides the route `page` file.

#9 was somehow related, but overall I think it's more of a different conventions vs missing features/conventions.

Let me know what you think!

**Comment by aladdin-add** [comment]
makes sense to me! 👍 

Another point: the new `app` is still experimental (the team does not recommend using it in production), and likely to be changed later. We can reconsider it when it reaches stable, and it's being widely accepted by the community!

**Comment by oedotme** [comment]
Awesome, thanks for sharing that!
