### ISSUE TITLE
Doesn't work with swc

### ISSUE THREAD

**Issue by t-animal** [oedotme/generouted#72]
When using  `"@vitejs/plugin-react-swc": "^3.1.0"` instead of `"@vitejs/plugin-react": "^3.1.0"`, running the app fails with an exception `2:50:04 PM [vite] Internal server error: Invalid glob import syntax: Expect CallExpression, got BinaryExpression`

**Comment by spa5k** [comment]
There seems to be some problems related with jsx tsx stuff and vite isn't compiling them (swc version)

**Comment by spa5k** [comment]
@oedotme since vite isnt considering tsx / jsx files, maybe we can do an experimental package if it works after transpiling it to latest JS ESNEXT (through tsup or rollup)

**Comment by oedotme** [comment]
@spa5k TBH, I'd vote to wait for `vite-plugin-react-swc` to support `jsx/tsx` as the current `vite-plugin-react`

**Comment by yogarasu** [comment]
@oedotme 
Am I correct in assuming that this repository does not currently work with Vite3?
If not, you should put a note in the README.

**Comment by spa5k** [comment]
It works with latest vite, you need to use react plugin, not the react plugin swc one

**Comment by oedotme** [comment]
Although it's recommended to use the latest Vite versions, Vite v3 still working fine with `generouted` and there's no reason for it not to work, the Vite APIs used are the same since v2 if I recall correctly.

This issue is about the new plugin for React with Vite based on `swc` not working as expected. It should work tho once the `swc` plugin supports `jsx/tsx` same as the other official React plugin based on `babel` and `esbuild`.

**Comment by ArnaudBarre** [comment]
Hi,

So turns out ts + dts file are not working to silence the error. So I think it's better to bundle the lib to avoid this kind of issue.

I still think we should push TS to better support this and I added support for transpiling TS files in node_modules in the SWC plugin (not released yet).

For info I think the modal is not working on the basic demo for react-router.

**Comment by oedotme** [comment]
Hey everyone, `@vitejs/plugin-react-swc` should be also compatible now with the latest `generouted` release at [v1.12.0](https://github.com/oedotme/generouted/releases/tag/v1.12.0). There are minor import changes needed for the upgrade and its included in the release notes.

I've tested it with the latest version `v3.2.0` and it's working :tada: That made possible by introducing bundling to `js` step for the published package as @spa5k [suggested here](https://github.com/oedotme/generouted/issues/72#issuecomment-1465208025).

I'm closing this now, please let me know if you have any issues with the `swc` plugin.
